#! /usr/bin/env ruby
# -*- coding: utf-8 -*-

#--
# NewsCrawler - a website crawler
#
# Copyright (C) 2013 - Hà Quang Dương <contact@haqduong.net>
#
# This file is part of NewsCrawler.
#
# NewsCrawler is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# NewsCrawler is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NewsCrawler.  If not, see <http://www.gnu.org/licenses/>.
#++

require 'news_crawler/config'
require 'news_crawler/nc_logger'

require 'news_crawler/processing/structure_analysis.rb'
require 'news_crawler/storage/url_queue'

include NewsCrawler::Storage

config = SimpleConfig.for :application

SimpleConfig.for :application do | conf |
  set :prefix, '' # set your prefix here
end

NewsCrawler::Storage::RawData.set_engine(config.db.engine.intern)
NewsCrawler::Storage::URLQueue.set_engine(config.db.engine.intern)
NewsCrawler::Storage::YAMLStor.set_engine(config.db.engine.intern)

URLQueue.mark_all('NewsCrawler::Processing::StructureAnalysis', URLQueue::UNPROCESSED)

processor = NewsCrawler::Processing::StructureAnalysis.new
